name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn build

      - name: Checkout Host Repo
        uses: actions/checkout@v2
        with:
          repository: IvanWoo/IvanWoo.github.io
          token: ${{ secrets.GH_PAT }}
          path: host-repo

      - name: Copy Out to Host Repo
        run: |
          rm -rf host-repo/key-finder
          mkdir host-repo/key-finder
          cp -a dist/. host-repo/key-finder

      - name: Commit Changes and Push
        run: |
          cd host-repo
          git config --local user.email "tyivanwu@gmail.com"
          git config --local user.name "Yifan Wu"
          git add -A
          if git diff --cached --quiet; then
            echo "ℹ️ No changes to commit, skipping deploy."
            exit 0
          fi
          git commit -m "🎵 key-finder updated at $(date +%Y-%m-%dT%H:%M:%S)"
          git push
